Hospital/Models/Appointment.cs
namespace Hospital.Models
{
    public class Appointment
    {
        public int Id { get; set; }
        public string PatientName { get; set; }
        public DateOnly AppointmentDate { get; set; }
        public TimeOnly AppointmentTime { get; set; }
        public int DoctorId { get; set; }
        public Doctor Doctor { get; set; }
    }
}

Hospital/Models/Doctor.cs
namespace Hospital.Models
{
    public class Doctor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Specialization { get; set; }
        public string Img { get; set; }

        public ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
    }
}

Hospital/Models/ErrorViewModel.cs
namespace Hospital.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hospital/Controllers/DoctorsController.cs
using Hospital.Data;
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Controllers
{
    public class DoctorsController : Controller
    {
        public IActionResult BookAppointment()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var doctors = context.Doctors.ToList();
            return View(doctors);
        }
        public IActionResult CompleteAppointment(int id)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var doctor = context.Doctors.Where(e=> e.Id == id).FirstOrDefault();
            if (doctor != null)
            {
                return View(doctor);
            }
            return RedirectToAction("NotFound");
        }

        public IActionResult SuccessReservation()
        {
            if (TempData.ContainsKey("AppointmentId"))
            {
                ApplicationDbContext context = new ApplicationDbContext();
                int appointmentId = (int)TempData["AppointmentId"];
                ViewBag.AppointmentId = appointmentId;
                var appointment = context.Appointments.Where(e => e.Id == appointmentId).FirstOrDefault();
                return View(appointment);
            }
            return RedirectToAction("NotFound");
        }
        public IActionResult NotFound() 
        {
            return View();
        }
        public IActionResult FailedReservation() 
        {
            return View();
        }

        public IActionResult AllAppointment() 
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var appointment = context.Appointments.Include(e=>e.Doctor).ToList();
            return View(appointment);
        }

        public IActionResult RemoveAppointment(int id)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var removed = context.Appointments.Where(e=>e.Id == id).FirstOrDefault();
            if (removed != null) {
                context.Appointments.Remove(removed);
                context.SaveChanges();
                return View(removed);
            }
            return RedirectToAction("NotFound");
        }

        [HttpPost]
        public IActionResult CompleteAppointment(string PatientName, DateOnly AppointmentDate, TimeOnly AppointmentTime, int DoctorId)
        {
            if (ModelState.IsValid) 
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var appointment = new Appointment
                {
                    PatientName = PatientName,
                    AppointmentDate = AppointmentDate,
                    AppointmentTime = AppointmentTime,
                    DoctorId = DoctorId
                };
                context.Appointments.Add(appointment);
                context.SaveChanges();

                TempData["AppointmentId"] = appointment.Id;

                return RedirectToAction("SuccessReservation");

            }
            return RedirectToAction("FailedReservation");
        }
    }
}

Hospital/Controllers/HomeController.cs
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hospital.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hospital/Views/Doctors/AllAppointment.cshtml
<h3>All Appointments</h3>
<br />
<br />

@foreach (var item in Model)
{
    var modalId = "staticBackdrop" + @item.Id;
    <div class="card" style="width: 22rem;">
        <div class="card-body">
            <h5 class="card-title">Patient Name: @item.PatientName</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Appointment Date: @item.AppointmentDate : @item.AppointmentTime </h6>
            <p class="card-text">Appointment Id: @item.Id - With: @item.Doctor.Name <br />Specialization: @item.Doctor.Specialization </p>



            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#@modalId">
                Delete Appointment
            </button>

            <!-- Modal -->
            <div class="modal fade" id="@modalId" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Delete Appointment</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure want to Delete Appointment?
                        </div>
                        <div class="modal-footer" >
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <a href="/Doctors/RemoveAppointment?id=@item.Id" class="btn btn-primary" style="background-color:red; border:none">Delete</a>
                        </div>
                    </div>
                </div>
            </div>


        </div>  
    </div>
}

Hospital/Views/Doctors/BookAppointment.cshtml
<h2>Book Appointment</h2>
@foreach (var item in Model)
{
    <div class="card" style="width: 20rem;">
        <img src="~/images/@item.Img" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@item.Name</h5>
            <p class="card-text">Specialization: @item.Specialization</p>
            <a href="/Doctors/CompleteAppointment?id=@item.Id" class="btn btn-primary">Book Appointment</a>
        </div>
    </div>
}

Hospital/Views/Doctors/CompleteAppointment.cshtml
<h2>Complete Appointment with @Model.Name</h2>
<br />
<form id="CompleteAppointment" method="post" action="/Doctors/CompleteAppointment">

    <label for="PatientName">Patient Name:</label>
    <input class="form-control" id="PatientName" type="text" name="PatientName" placeholder="Name" aria-label="default input example" required>

    <label for="AppointmentDate">Appointment Date:</label>
    <input class="form-control" id="AppointmentDate" name="AppointmentDate" type="date" placeholder="Default input" aria-label="default input example" required>

    <label for="AppointmentTime">Appointment Time:</label>
    <input class="form-control" id="AppointmentTime" name="AppointmentTime" type="time" placeholder="Default input" aria-label="default input example" required>
    <input type="hidden" value="@Model.Id" name="DoctorId" id="DoctorId" />
<br />
<button  class="btn btn-primary"> Complete Appointment</button>
</form>

Hospital/Views/Doctors/FailedReservation.cshtml
<head>
    <meta http-equiv="refresh" content="5;url=/Home/Index" />
</head>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="message-box _success _failed">
                <i class="fa fa-times-circle" aria-hidden="true"></i>
                <h2> Your Reservation failed </h2>
                <p>  Try again later </p>
                
            </div>
        </div>
    </div>
    <hr>
</div>


<div class="toast position-fixed bottom-0 end-0 p-3" style="width:400px;background-color:#fff;opacity:1" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
    <div class="toast-header">
        <strong class="me-auto">successful Reservation</strong>
        <small>1 second ago</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        You Will be Redirect to The Home Page in few seconds
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const toastElList = document.querySelectorAll('.toast');
        const toastList = [...toastElList].map(toastEl => new bootstrap.Toast(toastEl));
        toastList.forEach(toast => toast.show());
    });
</script>

Hospital/Views/Doctors/NotFound.cshtml
<style>href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"</style>
<div class="d-flex align-items-center justify-content-center vh-100">
<div class="text-center">
    <h1 class="display-1 fw-bold">404</h1>
    <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
    <p class="lead">
        The page you’re looking for doesn’t exist.
    </p>
    <br />
    <br />
    <a href="/Home/index" class="btn btn-primary" >Go Home</a>
</div>

Hospital/Views/Doctors/RemoveAppointment.cshtml
<h3 style="text-align:center">Remove Appointment successful</h3>
<hr class="hr hr-blurry" />
<br />
<br />
<div class="rmv-txt">
<h3>You removed the Appointment of Patient: @Model.PatientName</h3>
</div>
<div class="text-center" >
    <div class="rmv-btn">
        <a href="/Home/index" style="margin-top: 50px" class="btn btn-primary">Go Home</a>
    </div>
</div>

Hospital/Views/Doctors/SuccessReservation.cshtml
<head>
    <meta http-equiv="refresh" content="6;url=/Home/Index" />
</head>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="message-box _success">
                <i class="fa fa-check-circle" aria-hidden="true"></i>
                <h2> Your Reservation was successful </h2>
                <p>
                    Thank you for your Reservation Patient:@Model.PatientName <br>
                    Your reservation id is: @Model.Id
                    at: @Model.AppointmentDate
                </p>
            </div>
        </div>
    </div>
    <hr>
</div>


<div class="toast position-fixed bottom-0 end-0 p-3" style="width:400px;background-color:#fff;opacity:1" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
    <div class="toast-header">
        <strong class="me-auto">successful Reservation</strong>
        <small>1 second ago</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        You Will be Redirect to The Home Page in few seconds
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const toastElList = document.querySelectorAll('.toast');
        const toastList = [...toastElList].map(toastEl => new bootstrap.Toast(toastEl));
        toastList.forEach(toast => toast.show());
    });
</script>

Hospital/Views/Home/Index.cshtml
@* @{
    ViewData["Title"] = "Home Page";
}
 *@



<div class="text-center">
    <h1 class="display-4">Welcome to Our Hospital</h1>
    <p>Thank you for choosing our hospital for your healthcare needs.</p>
    <p>Here, we strive to provide the highest quality medical care to our patients.</p>
    <p> Learn more about our services and specialties:</p>

    <ul class="list-group">
        <li class="list-group-item"><a href="" class="list-group-anker">Internal Medicine</a></li>
        <li class="list-group-item"><a href="" class="list-group-anker">Pediatrics</a></li>
        <li class="list-group-item"><a href="" class="list-group-anker">Surgery</a></li>
    </ul>
    
    <p>If you need any further assistance or modifications, feel free to let me know!</p>
</div>

Hospital/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Welcome to Our Hospital</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hospital.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hospital</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="BookAppointment">Book an Appointment</a>
                        </li>
                    </ul>
                </div>
                <div >
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="AllAppointment">View All Appointments</a>
                        </li>
                        </ul>
                </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Hospital - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>